### PR TITLE
Improved Knee Testing

### LINKED ISSUE #28: Pregenerate / safe data for tests in designated folder
This should increase the speed of the test execution as generating data with knees and re-/downloading mne example data takes a lot of time

### PR DESCRIPTION
**Pull request by schmidtfa**
This pr aims to improve the knee testing functionality. When succesful we can close #28 and #29

### CODE REVIEW

**Comment by schmidtfa** [comment]
@thht  can you check this out and cache the mne stuff. I think we can close this issue afterwards :)

**Comment by thht** [comment]
> can you check this out and cache the mne stuff.

Actually, I don't think this makes much sense. Caching means that the data is tarred and gzipped and then uploaded to a host and the next job just downloads it and untars/gzips it. So, basically what fetching the dataset does in the first place.

An easier route would be to use the testing dataset instead of the sample one. It contains all the files you need and it is stored on `codeload.github.com` which should be an internal github server. This should increase the download speed because the sample dataset is hosted on osf which is an external server.

**Comment by schmidtfa** [comment]
Thanks for adding the files to lfs @thht. Tests seem to work so if you are happy lets merge and close some issues :)

**Comment by thht** [comment]
Sure, punch it!

**Pull request merged**
